import rhinoscriptsyntax as rs
rs.AddLayer("MyLayer1")
rs.AddLayer("MyLayer2", parent="MyLayer1")
rs.AddLayer("MyLayer3", parent="MyLayer2")
rs.AddLayer("MyLayer4", parent="MyLayer1")
rs.AddLayer("MyLayer5", parent="MyLayer2")
rs.AddLayer("MyLayer6", parent="MyLayer1")
rs.AddLayer("MyLayer7", parent="MyLayer2")
rs.AddLayer("MyLayer8", parent="MyLayer1")
rs.AddLayer("MyLayer9", parent="MyLayer2")
rs.AddLayer("MyLayer10", parent="MyLayer1")
rs.AddLayer("MyLayer11", parent="MyLayer2")
rs.AddLayer("MyLayer12", parent="MyLayer1")
rs.AddLayer("MyLayer13", parent="MyLayer2")